### ISSUE TITLE
ScrollPhysics

### ISSUE THREAD

**Issue by rvanderlinden** [robert-luoqing/section_view#3]
Hi!

I would like to use a different `ScrollPhysics` in the `SectionView` than the default. There is a parameter for it `physics`, but it appears to be unused. I have tried to set it to `physics: ClampingScrollPhysics()` which should not bounce on any platform, but it still bounces.

I was wondering whether the `physics` could simply be passed on to the `FlutterListView` in the `_renderList` function?

As a sidenote, `physics` is used in `_getPhysicsIsBounce` but the output of that function is not applied anywhere.

Thanks!

**Comment by robert-luoqing** [comment]
@rvanderlinden Thanks for your response. The issue fixed in section_view: ^2.0.5, please update it.

**Comment by rvanderlinden** [comment]
@robert-luoqing Thanks, its working now! :)
